require("danblc.plugins-setup")
require("danblc.core.options")
require("danblc.core.keymaps")
require("danblc.core.colorscheme")
require("danblc.plugins.comment")
require("danblc.plugins.nvim-tree")
require("danblc.plugins.lualine")
require("danblc.plugins.undotree")
