live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 16.0

# # Meslo
# [font.bold]
# family = "MesloLGS Nerd Font Mono"
# style = "Bold"
#
# [font.bold_italic]
# family = "MesloLGS Nerd Font Mono"
# style = "Bold Italic"
#
# [font.italic]
# family = "MesloLGS Nerd Font Mono"
# style = "Italic"
#
# [font.normal]
# family = "MesloLGS Nerd Font Mono"
# style = "Regular"

# Jetbrains
[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "SemiBold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Light"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"
# mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
#opacity = 0.97
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

# press F11 for full screen
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

#[debug]
#log_level = "Warn"
# Print all received window events.
#print_events = true
