live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "tmux"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
#opacity = 0.97
startup_mode = "Maximized"

[window.padding]
x = 3
y = 3

# press F11 for full screen
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

#[debug]
#log_level = "Warn"
# Print all received window events.
#print_events = true
